-- AuraSwap — Expose safe technical details on published property pages.
-- Keeps private owner contact fields out of the public view.

CREATE OR REPLACE VIEW public.public_properties_view
WITH (security_invoker = true) AS
SELECT
  id,
  host_id,
  title,
  description,
  type,
  value_rating,
  location,
  country,
  address,
  latitude,
  longitude,
  bedrooms,
  bathrooms,
  max_guests,
  aura_score,
  amenities,
  rules,
  is_published,
  is_featured,
  created_at,
  folder_status,
  meta_title,
  meta_description,
  meta_keywords,
  qr_code_url,
  short_code,
  short_link,
  updated_at,
  is_demo,
  desired_exchange,
  legal_public_deed,
  legal_tax_current,
  legal_debt_free,
  legal_services_paid,
  legal_owner_type,
  legal_is_mortgaged,
  primary_operation,
  development_name,
  subdivision_name,
  private_neighborhood,
  phase_stage,
  lot_number,
  block_number,
  condominium_regime,
  maintenance_fee_amount,
  neighborhood,
  postal_code,
  street_name,
  street_number,
  location_reference,
  show_public_address,
  half_bathrooms,
  parking_spaces,
  levels_count,
  construction_age,
  conservation_state_id,
  construction_type_id,
  surface_total,
  surface_built,
  surface_front,
  surface_depth,
  surface_garden,
  surface_terrace,
  surface_roof_garden,
  surface_patio,
  services_water,
  services_electricity,
  services_sewerage,
  services_nat_gas,
  services_lp_gas,
  services_internet,
  services_garbage,
  security_cctv,
  security_guardhouse,
  security_24_7,
  security_biometric,
  view_type_id,
  orientation_id
FROM public.properties
WHERE is_published = true;

GRANT SELECT ON public.public_properties_view TO anon, authenticated;
