"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MOCK_PROPERTIES = exports.USER_PROPERTIES = exports.CURRENT_USER = exports.MOCK_USERS = void 0;
exports.MOCK_USERS = [
    {
        id: 'current-user',
        name: 'Mateo Valenzuela',
        email: 'admin@auraswap.com',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
        isVerified: true,
        role: 'ADMIN', // Set as Administrator to enable CMS cockpit access
        properties: ['user-prop-1', 'user-prop-2'],
        favorites: ['prop-1', 'prop-4', 'prop-6'],
        swapsCount: 6,
        kycStatus: 'VERIFIED',
        joinDate: '2025-02-14'
    },
    {
        id: 'host-sofia',
        name: 'Sofia Alvarez',
        email: 'host@auraswap.com',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
        isVerified: true,
        role: 'HOST',
        properties: ['prop-1', 'prop-3'],
        favorites: ['user-prop-1'],
        swapsCount: 11,
        kycStatus: 'VERIFIED',
        joinDate: '2024-11-05'
    },
    {
        id: 'host-yuki',
        name: 'Yuki Sato',
        email: 'yuki@auraswap.com',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
        isVerified: true,
        role: 'HOST',
        properties: ['prop-4', 'prop-9'],
        favorites: [],
        swapsCount: 7,
        kycStatus: 'VERIFIED',
        joinDate: '2025-01-20'
    },
    {
        id: 'host-chloe',
        name: 'Chloé Laurent',
        email: 'chloe@auraswap.com',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80',
        isVerified: true,
        role: 'HOST',
        properties: ['prop-2', 'prop-8'],
        favorites: [],
        swapsCount: 9,
        kycStatus: 'VERIFIED',
        joinDate: '2024-09-12'
    },
    {
        id: 'host-giovanni',
        name: 'Giovanni Rossi',
        email: 'giovanni@auraswap.com',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
        isVerified: true,
        role: 'HOST',
        properties: ['prop-6', 'prop-7'],
        favorites: [],
        swapsCount: 8,
        kycStatus: 'VERIFIED',
        joinDate: '2024-05-18'
    },
    {
        id: 'host-elena',
        name: 'Elena Vidal',
        email: 'elena@auraswap.com',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
        isVerified: true,
        role: 'HOST',
        properties: ['prop-5'],
        favorites: [],
        swapsCount: 5,
        kycStatus: 'VERIFIED',
        joinDate: '2025-03-01'
    },
    {
        id: 'member-carlos',
        name: 'Carlos Mendoza',
        email: 'member@auraswap.com',
        avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
        isVerified: false,
        role: 'MEMBER', // Standard traveler member (KYC Pending)
        properties: [],
        favorites: ['prop-1', 'prop-2'],
        swapsCount: 0,
        kycStatus: 'PENDING',
        joinDate: '2026-04-10'
    }
];
exports.CURRENT_USER = exports.MOCK_USERS[0];
exports.USER_PROPERTIES = [
    {
        id: 'user-prop-1',
        title: 'Minimalist Shibuya Studio',
        description: 'A beautifully designed, compact architectural studio in the heart of Shibuya. Features a highly functional layout, custom warm white furniture, and a private balcony overlooking a peaceful street. Steps away from the iconic Shibuya Crossing, Michelin-starred ramen joints, and modern boutiques. Designed for digital nomads seeking seamless connection.',
        type: 'Apartment',
        location: 'Shibuya, Tokyo',
        country: 'Japan',
        address: '2-Chome Dogenzaka, Shibuya-ku, Tokyo, 150-0043',
        valueRating: 'Premium',
        images: [
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Wifi', 'Workstation', 'Air Conditioning', 'Washing Machine', 'Bicycles', 'Balcony'],
        auraScore: 99,
        bedrooms: 1,
        bathrooms: 1,
        maxGuests: 2,
        hostId: 'current-user',
        hostName: 'Mateo Valenzuela',
        hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.95,
        hostReviewsCount: 28,
        availableStart: '2026-06-01',
        availableEnd: '2026-12-31',
        latitude: 35.6580,
        longitude: 139.7016,
        isPublished: true,
        rules: [
            'No smoking inside the studio.',
            'Remove outdoor shoes at the genkan entry.',
            'Quiet hours after 10:00 PM.'
        ],
        reviews: [
            {
                id: 'rev-u1-1',
                authorName: 'Sofia Alvarez',
                authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
                rating: 5,
                date: '2026-04-12',
                comment: 'Un estudio de ensueño en Shibuya. Mateo fue un host increíble, dejó guías locales perfectas y la conexión de internet superó los 200Mbps. ¡Totalmente recomendado!'
            }
        ]
    },
    {
        id: 'user-prop-2',
        title: 'Forest Retreat Cabin',
        description: 'A striking A-frame architectural cabin nestled in the quiet pine forests of Karuizawa. Floor-to-ceiling glass grids frame towering green canopies, while a suspended wood-burning fireplace anchors the living room. Perfect for remote creators looking to isolate, hike, or listen to birds on the expansive outdoor deck.',
        type: 'Cabin',
        location: 'Karuizawa, Nagano',
        country: 'Japan',
        address: 'Karuizawamachi, Kitasaku District, Nagano, 389-0111',
        valueRating: 'Curated',
        images: [
            'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1449034446853-66c86144b0ad?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Fireplace', 'Outdoor Deck', 'Coffee Station', 'Mountain View', 'Hiking Trails', 'High-Speed Starlink'],
        auraScore: 97,
        bedrooms: 2,
        bathrooms: 1.5,
        maxGuests: 4,
        hostId: 'current-user',
        hostName: 'Mateo Valenzuela',
        hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.95,
        hostReviewsCount: 28,
        availableStart: '2026-06-01',
        availableEnd: '2026-12-31',
        latitude: 36.3508,
        longitude: 138.6358,
        isPublished: true,
        rules: [
            'Separate recyclables according to local guidelines.',
            'Be careful with dry firewood near the outdoor deck.',
            'Pets allowed with prior host confirmation.'
        ],
        reviews: []
    }
];
exports.MOCK_PROPERTIES = [
    {
        id: 'prop-1',
        title: 'Modernist Concrete Villa',
        description: 'Perched overlooking the azure ocean waters of Cancun, this striking raw concrete structure features clean brutalist lines mixed with elegant tropical details. Massive floor-to-ceiling sliding glass panels dissolve all barriers between the indoor open lounge, the zero-edge infinity pool, and a private sandy beach cove. Fully staffed for a premium stay.',
        type: 'Villa',
        location: 'Cancun, Quintana Roo',
        country: 'Mexico',
        address: 'Km 14.5 Blvd. Kukulcan, Zona Hotelera, Cancun, Q.R., 77500',
        valueRating: 'Luxury',
        images: [
            'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Infinity Pool', 'Private Beach', 'Chef Kitchen', 'Home Theater', 'Ocean Views', 'Paddleboards', 'Tesla Charger'],
        auraScore: 98,
        bedrooms: 4,
        bathrooms: 4.5,
        maxGuests: 8,
        hostId: 'host-sofia',
        hostName: 'Sofia Alvarez',
        hostAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.98,
        hostReviewsCount: 42,
        availableStart: '2026-06-15',
        availableEnd: '2026-10-15',
        latitude: 21.1619,
        longitude: -86.8515,
        isPublished: true,
        rules: [
            'No loud music outdoors after 11:00 PM.',
            'Shower off beach sand before entering the infinity pool.',
            'Only registered swap guests allowed overnight.'
        ],
        reviews: [
            {
                id: 'rev-1-1',
                authorName: 'Mateo Valenzuela',
                authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
                rating: 5,
                date: '2025-12-10',
                comment: 'Absolutamente sublime. Las vistas del amanecer desde la piscina de concreto son una obra de arte. Sofia coordinó todo con extrema delicadeza. Recomiendo usar sus paddleboards al amanecer.'
            },
            {
                id: 'rev-1-2',
                authorName: 'Chloé Laurent',
                authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80',
                rating: 5,
                date: '2026-02-05',
                comment: 'The architectural design is world-class. It felt like living inside a modern design museum. Exceptional cleanliness and absolute privacy.'
            }
        ]
    },
    {
        id: 'prop-2',
        title: '17th-Century Marais Loft',
        description: 'Step into historical elegance in Paris. Located in the fashionable Marais district, this apartment boasts original heavy hand-carved oak beams, exposed white limestone blocks, and curation of modern mid-century items. Soaring windows flood the loft with romantic north light, looking out onto classic grey Parisian zinc roofs and secret courtyards.',
        type: 'Loft',
        location: 'Le Marais, Paris',
        country: 'France',
        address: '42 Rue des Francs Bourgeois, 75003 Paris',
        valueRating: 'Exclusive',
        images: [
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1499955085172-a104c9463ece?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Espresso Bar', 'Vintage Record Player', 'Library', 'French Balcony', 'High-Speed Wifi', 'Dyson Airwrap'],
        auraScore: 96,
        bedrooms: 1,
        bathrooms: 1,
        maxGuests: 2,
        hostId: 'host-chloe',
        hostName: 'Chloé Laurent',
        hostAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.91,
        hostReviewsCount: 56,
        availableStart: '2026-07-01',
        availableEnd: '2026-09-30',
        latitude: 48.8584,
        longitude: 2.3522,
        isPublished: true,
        rules: [
            'Please respect our quiet Parisian neighbors; no parties.',
            'Use only wool-safe cleaners on the antique Persian rugs.',
            'Water the balcony hydrangeas once every three days.'
        ],
        reviews: [
            {
                id: 'rev-2-1',
                authorName: 'Yuki Sato',
                authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
                rating: 5,
                date: '2025-10-18',
                comment: 'A true designer sanctuary. Chloé has collection of vinyl records that made our evenings magical. Located near the best galleries and bakeries.'
            }
        ]
    },
    {
        id: 'prop-3',
        title: 'Bauhaus Penthouse overlooking CDMX',
        description: 'A spectacular penthouse in leafy Roma Norte. Impeccable industrial architecture inspired by the Bauhaus school, containing custom steel-frame window grids, dark concrete finishes, and an expansive private terrace garden overflowing with indigenous Mexican plants. A quiet, high-altitude design sanctuary in the best culinary zone.',
        type: 'Penthouse',
        location: 'Roma Norte, Mexico City',
        country: 'Mexico',
        address: 'Calle Colima 184, Roma Norte, Ciudad de México, 06700',
        valueRating: 'Premium',
        images: [
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Rooftop Garden', 'Dedicated Workspace', 'Chef Stove', 'Espresso Maker', 'Bicycles', 'Art Collection'],
        auraScore: 95,
        bedrooms: 2,
        bathrooms: 2,
        maxGuests: 4,
        hostId: 'host-sofia',
        hostName: 'Sofia Alvarez',
        hostAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.98,
        hostReviewsCount: 42,
        availableStart: '2026-06-01',
        availableEnd: '2026-12-31',
        latitude: 19.4184,
        longitude: -99.1611,
        isPublished: true,
        rules: [
            'Use the terrace ash trays; strictly no smoking inside.',
            'Feel free to borrow the retro road bicycles, but lock them securely.',
            'Check out by 11:00 AM to allow garden pruning.'
        ],
        reviews: []
    },
    {
        id: 'prop-4',
        title: 'Tropical Ubud Sanctuary',
        description: 'Immerse yourself in jungle calm. This striking bamboo villa in Ubud features an open-concept structure that flows into the surrounding tropical forests and a natural private pool. Listen to the whispers of the river and enjoy breakfast views across pristine rice fields.',
        type: 'Villa',
        location: 'Ubud, Bali',
        country: 'Indonesia',
        address: 'Jalan Raya Sanggingan, Ubud, Gianyar, Bali, 80571',
        valueRating: 'Luxury',
        images: [
            'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Infinity Pool', 'Semi-Outdoor Shower', 'Scooters Included', 'Yoga Deck', 'Rice Terrace Views', 'Fully Staffed'],
        auraScore: 94,
        bedrooms: 3,
        bathrooms: 3.5,
        maxGuests: 6,
        hostId: 'host-yuki',
        hostName: 'Yuki Sato',
        hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.97,
        hostReviewsCount: 19,
        availableStart: '2026-08-01',
        availableEnd: '2026-11-30',
        latitude: -8.5069,
        longitude: 115.2625,
        isPublished: true,
        rules: [
            'Eco-resort rules apply: minimize plastic usage.',
            'Local temple visits require sarong (provided in closet).',
            'Staff leaves at 5:00 PM; enjoy quiet jungle evenings.'
        ],
        reviews: [
            {
                id: 'rev-4-1',
                authorName: 'Mateo Valenzuela',
                authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
                rating: 5,
                date: '2026-01-14',
                comment: 'Despertar con la vista a los campos de arroz desde la ducha exterior fue algo espiritual. Yuki es un host muy respetuoso y atento. ¡Mágico!'
            }
        ]
    },
    {
        id: 'prop-5',
        title: 'Salamanca Classic Apartment',
        description: 'A beautiful historical apartment in the heart of Madrid’s upscale Salamanca district. Soaring ceilings with detailed crown plasterwork, dark herringbone oak floors, and light-filled French balconies overlooking a quiet boutique shopping street. Elegantly curated art collection.',
        type: 'Apartment',
        location: 'Salamanca, Madrid',
        country: 'Spain',
        address: 'Calle de Claudio Coello 88, 28006 Madrid',
        valueRating: 'Curated',
        images: [
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['French Balcony', 'Vintage Record Player', 'High-Speed Wifi', 'Espresso Maker', 'Bicycles', 'Art Collection'],
        auraScore: 92,
        bedrooms: 2,
        bathrooms: 2,
        maxGuests: 4,
        hostId: 'host-elena',
        hostName: 'Elena Vidal',
        hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.90,
        hostReviewsCount: 31,
        availableStart: '2026-06-01',
        availableEnd: '2026-12-15',
        latitude: 40.4300,
        longitude: -3.6850,
        isPublished: true,
        rules: [
            'Quiet hours from 10:00 PM to 8:00 AM according to Madrid ordinances.',
            'No commercial photoshoots allowed without host agreement.',
            'Turn off high-output AC units when leaving the apartment.'
        ],
        reviews: []
    },
    {
        id: 'prop-6',
        title: 'Renaissance Tuscan Stone Villa',
        description: 'An ancient 16th-century stone farmhouse masterfully updated with premium minimalist Italian design. Set amidst rolling olive groves and rows of grapes in Tuscany, it features massive timber beam ceilings, brick arches, a large open hearth fireplace, and a private heated courtyard pool.',
        type: 'Villa',
        location: 'Florence, Tuscany',
        country: 'Italy',
        address: 'Via di Marignolle 24, 50124 Firenze FI, Italy',
        valueRating: 'Luxury',
        images: [
            'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Infinity Pool', 'Fireplace', 'Outdoor Deck', 'Chef Kitchen', 'Espresso Maker', 'Hiking Trails', 'Art Collection'],
        auraScore: 97,
        bedrooms: 5,
        bathrooms: 5,
        maxGuests: 10,
        hostId: 'host-giovanni',
        hostName: 'Giovanni Rossi',
        hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.96,
        hostReviewsCount: 37,
        availableStart: '2026-05-01',
        availableEnd: '2026-10-31',
        latitude: 43.7400,
        longitude: 11.2300,
        isPublished: true,
        rules: [
            'Do not pick olives/grapes without coordination.',
            'Pool heating operates strictly via timer settings.',
            'Waste separation rules are extremely strict in the valley.'
        ],
        reviews: [
            {
                id: 'rev-6-1',
                authorName: 'Sofia Alvarez',
                authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
                rating: 5,
                date: '2025-09-22',
                comment: 'Giovanni has created a paradise. The blend of raw Renaissance stone and sleek metal Boffi kitchen is breathtaking. We swaps again next year!'
            }
        ]
    },
    {
        id: 'prop-7',
        title: 'Amalfi Coast Cliffside Villa',
        description: 'An architectural marvel hanging off the sheer cliffs of Positano. Steep terraces cascade down to private ocean ladders, surrounded by fragrant lemon orchards. High-vaulted plaster ceilings and hand-painted blue Majolica floor tiles frame absolute views of the sparkling Mediterranean.',
        type: 'Villa',
        location: 'Positano, Amalfi',
        country: 'Italy',
        address: 'Via Pasitea 190, 84017 Positano SA, Italy',
        valueRating: 'Exclusive',
        images: [
            'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Ocean Views', 'Private Beach', 'Chef Kitchen', 'Espresso Maker', 'Outdoor Deck', 'Fully Staffed'],
        auraScore: 95,
        bedrooms: 3,
        bathrooms: 3.5,
        maxGuests: 6,
        hostId: 'host-giovanni',
        hostName: 'Giovanni Rossi',
        hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.96,
        hostReviewsCount: 37,
        availableStart: '2026-06-01',
        availableEnd: '2026-09-30',
        latitude: 40.6281,
        longitude: 14.4850,
        isPublished: true,
        rules: [
            'Steps to the water ladders are steep; use caution.',
            'Water utility in Positano is scarce; please conserve.',
            'Check-in must happen before sunset for luggage portage.'
        ],
        reviews: []
    },
    {
        id: 'prop-8',
        title: 'French Riviera Minimalist Estate',
        description: 'Situated near Nice, this ultra-luxurious steel-and-glass structural villa provides sweeping panoramic views of the French Riviera. A completely private olive garden surround a massive heated mirror pool. Elegant Boffi chef kitchen, custom lighting, and bespoke minimalist furniture throughout.',
        type: 'Villa',
        location: 'Nice, Côte d\'Azur',
        country: 'France',
        address: 'Boulevard de la Corne d\'Or, 06230 Villefranche-sur-Mer',
        valueRating: 'Luxury',
        images: [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Infinity Pool', 'Ocean Views', 'Chef Kitchen', 'Tesla Charger', 'Espresso Maker', 'Fully Staffed'],
        auraScore: 94,
        bedrooms: 4,
        bathrooms: 4.5,
        maxGuests: 8,
        hostId: 'host-chloe',
        hostName: 'Chloé Laurent',
        hostAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.91,
        hostReviewsCount: 56,
        availableStart: '2026-06-01',
        availableEnd: '2026-10-15',
        latitude: 43.7000,
        longitude: 7.2600,
        isPublished: true,
        rules: [
            'Smart home controls must not be hard reset.',
            'No high heels on the custom matte lacquer wood floorboards.',
            'Pool cover must be closed nightly to maintain heat.'
        ],
        reviews: []
    },
    {
        id: 'prop-9',
        title: 'Kyoto Machiya Heritage House',
        description: 'An meticulously preserved Kyoto Machiya wooden townhouse in historic Gion. Features authentic tatami-mat rooms, paper shoji sliding panels, an ancient private dry stone zen rock garden, and a deep soaking Hinoki cedar tub (Ofuro). Blends 100-year history with quiet designer comforts.',
        type: 'Apartment',
        location: 'Gion, Kyoto',
        country: 'Japan',
        address: '570-Gionmachi Minamigawa, Higashiyama-ku, Kyoto, 605-0074',
        valueRating: 'Exclusive',
        images: [
            'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1601042879364-f3947d3f9c16?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Library', 'Espresso Maker', 'High-Speed Wifi', 'Bicycles', 'Zen Garden', 'Hinoki Soaking Tub'],
        auraScore: 98,
        bedrooms: 2,
        bathrooms: 1.5,
        maxGuests: 4,
        hostId: 'host-yuki',
        hostName: 'Yuki Sato',
        hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.97,
        hostReviewsCount: 19,
        availableStart: '2026-06-01',
        availableEnd: '2026-12-31',
        latitude: 35.0037,
        longitude: 135.7782,
        isPublished: true,
        rules: [
            'No suitcases allowed directly on the tatami mats; use closet mats.',
            'Keep the sliding Shoji frames clean and dry.',
            'Hinoki tub requires rinsing with clean water only, no harsh soaps.'
        ],
        reviews: [
            {
                id: 'rev-9-1',
                authorName: 'Mateo Valenzuela',
                authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
                rating: 5,
                date: '2026-03-10',
                comment: 'Hospedarse aquí es retroceder en el tiempo con todas las comodidades modernas. Bañarse en la tina de Hinoki contemplando el jardín de rocas nevado es un recuerdo de por vida.'
            }
        ]
    },
    {
        id: 'prop-10',
        title: 'Ibiza Cliffside Modern Estate',
        description: 'An absolute design masterpiece hanging over the Mediterranean cliffs in Ibiza. Glass walls retract fully, creating a single continuous zone that spans the living area, dynamic limestone terrace, and the private infinity pool. Features a private beach cove path, sound systems, and panoramic sunset views.',
        type: 'Villa',
        location: 'Cala Vadella, Ibiza',
        country: 'Spain',
        address: 'Calle Cala Vadella 45, Sant Josep de sa Talaia, Ibiza, 07830',
        valueRating: 'Luxury',
        images: [
            'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Infinity Pool', 'Private Beach', 'Ocean Views', 'Chef Kitchen', 'Tesla Charger', 'Sonos System'],
        auraScore: 99,
        bedrooms: 4,
        bathrooms: 4.5,
        maxGuests: 8,
        hostId: 'host-sofia',
        hostName: 'Sofia Alvarez',
        hostAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.98,
        hostReviewsCount: 42,
        availableStart: '2026-06-01',
        availableEnd: '2026-10-31',
        latitude: 38.9200,
        longitude: 1.2200,
        isPublished: true,
        rules: [
            'No parties without express written authorization.',
            'Eco preservation guidelines apply; switch off outdoor spotlights by midnight.',
            'Only registered hosts allowed on private stairs leading to the cove.'
        ],
        reviews: []
    },
    {
        id: 'demo-sale-tres-rios',
        title: 'Casa Residencial — Tres Ríos',
        description: 'Hermosa casa residencial en la exclusiva zona de Tres Ríos con acabados de primera y espacios ideales para toda la familia.',
        type: 'Villa',
        location: 'Tres Ríos, Culiacán',
        country: 'México',
        address: 'Tres Ríos, Culiacán, Sinaloa, México',
        valueRating: 'Premium',
        images: [
            'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Cocina con isla', 'Jardín', 'Cuarto de lavado', 'Sala', 'Comedor'],
        auraScore: 95,
        bedrooms: 3,
        bathrooms: 3.5,
        maxGuests: 6,
        hostId: 'host-eterna',
        hostName: 'Eterna Asesoría',
        hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.9,
        hostReviewsCount: 15,
        availableStart: '2026-01-01',
        availableEnd: '2026-12-31',
        latitude: 24.8053,
        longitude: -107.3940,
        isPublished: true,
        rules: ['Respetar reglamento vecinal.', 'No eventos ruidosos.'],
        reviews: [],
        offerings: [
            {
                id: 'offering-demo-sale-tres-rios',
                propertyId: 'demo-sale-tres-rios',
                mode: 'SALE',
                status: 'ACTIVE',
                visibility: 'PUBLIC',
                title: 'Casa Residencial — Tres Ríos',
                description: 'Hermosa casa residencial en la exclusiva zona de Tres Ríos con acabados de primera y espacios ideales para toda la familia.',
                priceAmount: 5950000,
                currency: 'MXN',
                billingPeriod: 'NONE',
                isPriceNegotiable: true,
                acceptsOffers: true,
                requiresApproval: false,
                allowInstantRequest: true,
                swapPreferences: {},
                isFeatured: false,
                featuredRank: 0,
                metadata: {}
            }
        ]
    },
    {
        id: 'demo-sale-marina-mazatlan',
        title: 'Departamento Marina Mazatlán',
        description: 'Espectacular departamento en Marina Mazatlán con amenidades premium y una vista inigualable.',
        type: 'Apartment',
        location: 'Marina Mazatlán, Mazatlán',
        country: 'México',
        address: 'Marina Mazatlán, Mazatlán, Sinaloa, México',
        valueRating: 'Exclusive',
        images: [
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Vista al mar', 'Terraza', 'Alberca', 'Gimnasio', 'Seguridad 24/7'],
        auraScore: 94,
        bedrooms: 2,
        bathrooms: 2,
        maxGuests: 4,
        hostId: 'host-eterna',
        hostName: 'Eterna Asesoría',
        hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.9,
        hostReviewsCount: 15,
        availableStart: '2026-01-01',
        availableEnd: '2026-12-31',
        latitude: 23.2494,
        longitude: -106.4111,
        isPublished: true,
        rules: ['Prohibido fumar.', 'Mantener el orden en áreas comunes.'],
        reviews: [],
        offerings: [
            {
                id: 'offering-demo-sale-marina-mazatlan',
                propertyId: 'demo-sale-marina-mazatlan',
                mode: 'SALE',
                status: 'ACTIVE',
                visibility: 'PUBLIC',
                title: 'Departamento Marina Mazatlán',
                description: 'Espectacular departamento en Marina Mazatlán con amenidades premium y una vista inigualable.',
                priceAmount: 6750000,
                currency: 'MXN',
                billingPeriod: 'NONE',
                isPriceNegotiable: true,
                acceptsOffers: true,
                requiresApproval: false,
                allowInstantRequest: true,
                swapPreferences: {},
                isFeatured: false,
                featuredRank: 0,
                metadata: {}
            }
        ]
    },
    {
        id: 'demo-sale-la-primavera',
        title: 'Casa La Primavera',
        description: 'Exclusiva residencia premium en La Primavera con amplios espacios, cochera techada para tres autos y áreas recreativas.',
        type: 'Villa',
        location: 'La Primavera, Culiacán',
        country: 'México',
        address: 'La Primavera, Culiacán, Sinaloa, México',
        valueRating: 'Premium',
        images: [
            'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Alberca', 'Roof Garden', 'Oficina', 'Jardín', 'Cochera 3 autos'],
        auraScore: 97,
        bedrooms: 4,
        bathrooms: 4.5,
        maxGuests: 8,
        hostId: 'host-eterna',
        hostName: 'Eterna Asesoría',
        hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.9,
        hostReviewsCount: 15,
        availableStart: '2026-01-01',
        availableEnd: '2026-12-31',
        latitude: 24.8053,
        longitude: -107.3940,
        isPublished: true,
        rules: ['Acceso controlado.', 'Respetar áreas verdes.'],
        reviews: [],
        offerings: [
            {
                id: 'offering-demo-sale-la-primavera',
                propertyId: 'demo-sale-la-primavera',
                mode: 'SALE',
                status: 'ACTIVE',
                visibility: 'PUBLIC',
                title: 'Casa La Primavera',
                description: 'Exclusiva residencia premium en La Primavera con amplios espacios, cochera techada para tres autos y áreas recreativas.',
                priceAmount: 8450000,
                currency: 'MXN',
                billingPeriod: 'NONE',
                isPriceNegotiable: true,
                acceptsOffers: true,
                requiresApproval: false,
                allowInstantRequest: true,
                swapPreferences: {},
                isFeatured: false,
                featuredRank: 0,
                metadata: {}
            }
        ]
    },
    {
        id: 'demo-rent-zona-dorada',
        title: 'Departamento Zona Dorada',
        description: 'Acogedor departamento amueblado en la Zona Dorada de Mazatlán con alberca y seguridad permanente.',
        type: 'Apartment',
        location: 'Zona Dorada, Mazatlán',
        country: 'México',
        address: 'Zona Dorada, Mazatlán, Sinaloa, México',
        valueRating: 'Curated',
        images: [
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Amueblado', 'Alberca', 'Balcón', 'Elevador', 'Seguridad'],
        auraScore: 93,
        bedrooms: 2,
        bathrooms: 2,
        maxGuests: 4,
        hostId: 'host-eterna',
        hostName: 'Eterna Asesoría',
        hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.9,
        hostReviewsCount: 15,
        availableStart: '2026-01-01',
        availableEnd: '2026-12-31',
        latitude: 23.2494,
        longitude: -106.4111,
        isPublished: true,
        rules: ['No se permiten mascotas.', 'Límite de 4 huéspedes.'],
        reviews: [],
        offerings: [
            {
                id: 'offering-demo-rent-zona-dorada',
                propertyId: 'demo-rent-zona-dorada',
                mode: 'MONTHLY_RENT',
                status: 'ACTIVE',
                visibility: 'PUBLIC',
                title: 'Departamento Zona Dorada',
                description: 'Acogedor departamento amueblado en la Zona Dorada de Mazatlán con alberca y seguridad permanente.',
                priceAmount: 24500,
                currency: 'MXN',
                billingPeriod: 'MONTH',
                isPriceNegotiable: true,
                acceptsOffers: true,
                requiresApproval: false,
                allowInstantRequest: true,
                swapPreferences: {},
                isFeatured: false,
                featuredRank: 0,
                metadata: {}
            }
        ]
    },
    {
        id: 'demo-rent-montebello',
        title: 'Casa Montebello',
        description: 'Excelente residencia de renta en Montebello ubicada en una privada muy tranquila con cochera cerrada y cocina integral.',
        type: 'Villa',
        location: 'Montebello, Culiacán',
        country: 'México',
        address: 'Montebello, Culiacán, Sinaloa, México',
        valueRating: 'Curated',
        images: [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Estudio', 'Jardín', 'Privada', 'Cochera', 'Cocina integral'],
        auraScore: 92,
        bedrooms: 3,
        bathrooms: 3,
        maxGuests: 6,
        hostId: 'host-eterna',
        hostName: 'Eterna Asesoría',
        hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.9,
        hostReviewsCount: 15,
        availableStart: '2026-01-01',
        availableEnd: '2026-12-31',
        latitude: 24.8053,
        longitude: -107.3940,
        isPublished: true,
        rules: ['Se solicita depósito en garantía.', 'Contrato mínimo de 6 meses.'],
        reviews: [],
        offerings: [
            {
                id: 'offering-demo-rent-montebello',
                propertyId: 'demo-rent-montebello',
                mode: 'MONTHLY_RENT',
                status: 'ACTIVE',
                visibility: 'PUBLIC',
                title: 'Casa Montebello',
                description: 'Excelente residencia de renta en Montebello ubicada en una privada muy tranquila con cochera cerrada y cocina integral.',
                priceAmount: 32000,
                currency: 'MXN',
                billingPeriod: 'MONTH',
                isPriceNegotiable: true,
                acceptsOffers: true,
                requiresApproval: false,
                allowInstantRequest: true,
                swapPreferences: {},
                isFeatured: false,
                featuredRank: 0,
                metadata: {}
            }
        ]
    },
    {
        id: 'demo-rent-malecon-mazatlan',
        title: 'Departamento Malecón Mazatlán',
        description: 'Premium departamento frente al malecón de Mazatlán con alberca infinity, gimnasio y vistas espectaculares al océano.',
        type: 'Apartment',
        location: 'Malecón, Mazatlán',
        country: 'México',
        address: 'Malecón, Mazatlán, Sinaloa, México',
        valueRating: 'Luxury',
        images: [
            'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'
        ],
        amenities: ['Vista al mar', 'Terraza', 'Alberca Infinity', 'Gimnasio', 'Estacionamiento techado'],
        auraScore: 96,
        bedrooms: 3,
        bathrooms: 2,
        maxGuests: 6,
        hostId: 'host-eterna',
        hostName: 'Eterna Asesoría',
        hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
        hostVerified: true,
        hostRating: 4.9,
        hostReviewsCount: 15,
        availableStart: '2026-01-01',
        availableEnd: '2026-12-31',
        latitude: 23.2494,
        longitude: -106.4111,
        isPublished: true,
        rules: ['Reglamento condominal estricto.', 'No ruido molesto después de las 10 PM.'],
        reviews: [],
        offerings: [
            {
                id: 'offering-demo-rent-malecon-mazatlan',
                propertyId: 'demo-rent-malecon-mazatlan',
                mode: 'MONTHLY_RENT',
                status: 'ACTIVE',
                visibility: 'PUBLIC',
                title: 'Departamento Malecón Mazatlán',
                description: 'Premium departamento frente al malecón de Mazatlán con alberca infinity, gimnasio y vistas espectaculares al océano.',
                priceAmount: 38000,
                currency: 'MXN',
                billingPeriod: 'MONTH',
                isPriceNegotiable: true,
                acceptsOffers: true,
                requiresApproval: false,
                allowInstantRequest: true,
                swapPreferences: {},
                isFeatured: false,
                featuredRank: 0,
                metadata: {}
            }
        ]
    }
];
