import type { LucideIcon } from 'lucide-react';
import {
  Archive,
  Armchair,
  AudioLines,
  Bath,
  BedSingle,
  Blocks,
  BriefcaseBusiness,
  Building2,
  Cable,
  ChefHat,
  CircleParking,
  Clapperboard,
  Coffee,
  Compass,
  ConciergeBell,
  CookingPot,
  Dumbbell,
  Expand,
  Fence,
  Flame,
  FlameKindling,
  Flower2,
  Gamepad2,
  Goal,
  HeartPulse,
  HousePlug,
  LampDesk,
  Laptop,
  Library,
  LockKeyhole,
  Martini,
  Medal,
  Monitor,
  MoveVertical,
  PawPrint,
  PersonStanding,
  PlugZap,
  Shirt,
  Shapes,
  Sofa,
  SolarPanel,
  Sparkles,
  Sprout,
  SunMedium,
  ThermometerSun,
  Trees,
  Trophy,
  Tv,
  Users,
  UsersRound,
  UtensilsCrossed,
  WashingMachine,
  Waves,
  Wifi,
  Wind,
  Wine,
} from 'lucide-react';

const PROPERTY_FEATURE_ICONS: Record<string, LucideIcon> = {
  'Cocina integral': CookingPot,
  'Cocina equipada': ChefHat,
  'Cocina con isla': CookingPot,
  Desayunador: Coffee,
  Sala: Sofa,
  Comedor: UtensilsCrossed,
  'Sala doble altura': Expand,
  'Family Room': Armchair,
  'Sala TV': Tv,
  Biblioteca: Library,
  Oficina: BriefcaseBusiness,
  Estudio: LampDesk,
  'Cuarto de servicio': BedSingle,
  'Cuarto de lavado': WashingMachine,
  Vestidor: Shirt,
  Bodega: Archive,
  Bar: Martini,
  Cava: Wine,
  Terraza: SunMedium,
  'Roof Garden': Sprout,
  Jardín: Flower2,
  Patio: Fence,
  Balcón: Building2,

  Alberca: Waves,
  Jacuzzi: Bath,
  Sauna: ThermometerSun,
  Asador: FlameKindling,
  Huerto: Sprout,
  Cancha: Trophy,
  Domótica: HousePlug,
  Alexa: AudioLines,
  'Cerradura inteligente': LockKeyhole,
  'Paneles solares': SolarPanel,
  'Cargador vehículo eléctrico': PlugZap,
  'Internet fibra óptica': Cable,

  'Alberca compartida': Waves,
  Gimnasio: Dumbbell,
  'Roof Garden compartido': Sprout,
  'Terraza común': SunMedium,
  'Jardín común': Trees,
  'Salón de usos múltiples': UsersRound,
  Coworking: Laptop,
  'Business center': BriefcaseBusiness,
  'Cinema room': Clapperboard,
  'Sports room': Medal,
  'Yoga room': PersonStanding,
  'Social room': UsersRound,
  Ludoteca: Shapes,
  'Game room': Gamepad2,
  'Área de juegos infantiles': Blocks,
  'Pet center': PawPrint,
  'Fire pit': Flame,
  'Cancha deportiva compartida': Goal,
  'Spa compartido': HeartPulse,
  'Estacionamiento para visitas': CircleParking,
  Elevador: MoveVertical,
  'Lobby / recepción': ConciergeBell,

  Wifi,
  Workstation: Monitor,
  'Air Conditioning': Wind,
  'Washing Machine': WashingMachine,
  Bicycles: Compass,
  Balcony: Building2,
  Fireplace: Flame,
  'Outdoor Deck': SunMedium,
  'Coffee Station': Coffee,
  'Mountain View': Trees,
  'Hiking Trails': Compass,
  'High-Speed Starlink': Wifi,
  'Infinity Pool': Waves,
  'Private Beach': Waves,
  'Chef Kitchen': ChefHat,
  'Home Theater': Clapperboard,
  'Ocean Views': Waves,
  Paddleboards: Waves,
  'Tesla Charger': PlugZap,
  'Espresso Bar': Coffee,
  'Vintage Record Player': AudioLines,
  Library,
  'French Balcony': Building2,
  'Dyson Airwrap': Wind,
  'Rooftop Garden': Sprout,
  'Dedicated Workspace': Laptop,
  'Chef Stove': CookingPot,
  'Espresso Maker': Coffee,
  'Art Collection': Sparkles,
  'Semi-Outdoor Shower': Bath,
  'Scooters Included': Compass,
  'Yoga Deck': PersonStanding,
  'Rice Terrace Views': Trees,
  'Fully Staffed': Users,
  'Professional Grade Range': CookingPot,
  'Backyard Deck': Fence,
  'Infrared Sauna': ThermometerSun,
  Piano: AudioLines,
  'Office Workspace': BriefcaseBusiness,
  'Sonos System': AudioLines,
};

export function getPropertyFeatureIcon(feature: string): LucideIcon {
  return PROPERTY_FEATURE_ICONS[feature] || Compass;
}

