-- Minimal public asking-price evidence verified on 2026-08-09 (local time).
-- No descriptions, contact details, photos or seller identities are stored.

select public.ingest_research_market_observations(
  $source${
    "source_code":"propiedades-com",
    "organization":"Propiedades.com",
    "name":"Propiedades.com — fichas públicas verificadas",
    "official_url":"https://propiedades.com/",
    "geographic_scope":"México",
    "update_frequency":"on-demand",
    "license_name":"Investigación comparativa de anuncios públicos",
    "license_url":null,
    "metadata":{
      "usageAuthorization":"RESEARCH_ONLY",
      "accessMethod":"PUBLIC_WEB_RESEARCH",
      "researchBasis":"user-directed-comparative-market-research",
      "researchScope":"minimal-asking-price-comparables",
      "visibility":"internal",
      "storedFieldsExclude":["phone","email","fullDescription","photos","sellerIdentity"]
    }
  }$source$::jsonb,
  $rows$[
    {"source_code":"propiedades-com","external_reference":"30939119","source_url":"https://propiedades.com/inmuebles/casa-en-venta-parque-foresta-lomas-de-angelopolis-iii-72830-lomas-de-angelopolis-pue-lomas-de-angelopolis-puebla-30939119","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Lomas de Angelópolis","neighborhood":"Lomas de Angelópolis","city":"San Andrés Cholula","state":"Puebla","price_amount":6150000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":4,"bathrooms":5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":251,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30939119","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"31137600","source_url":"https://propiedades.com/inmuebles/casa-en-venta-parque-colima-1-lomas-de-angelopolis-puebla-31137600","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Lomas de Angelópolis","neighborhood":"Lomas de Angelópolis","city":"San Andrés Cholula","state":"Puebla","price_amount":5290000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":296,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-31137600","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30980354","source_url":"https://propiedades.com/inmuebles/casa-en-venta-parque-sinaloa-1-lomas-de-angelopolis-puebla-30980354","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Lomas de Angelópolis","neighborhood":"Lomas de Angelópolis","city":"San Andrés Cholula","state":"Puebla","price_amount":5100000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":4,"bathrooms":5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":268,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30980354","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30966242","source_url":"https://propiedades.com/inmuebles/casa-en-venta-lomas-de-angelopolis-72966-san-bernardino-tlaxcalancingo-pue-lomas-de-angelopolis-puebla-30966242","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Lomas de Angelópolis","neighborhood":"Lomas de Angelópolis","city":"San Bernardino Tlaxcalancingo","state":"Puebla","price_amount":3120000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":3,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":140,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30966242","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30228370","source_url":"https://propiedades.com/inmuebles/casa-en-venta-blvd-reyes-lomas-de-angelopolis-puebla-30228370","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Lomas de Angelópolis","neighborhood":"Lomas de Angelópolis","city":"San Andrés Cholula","state":"Puebla","price_amount":6950000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":5,"bathrooms":5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":320,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30228370","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30731174","source_url":"https://propiedades.com/inmuebles/casa-en-venta-sierra-colorada-77-lomas-de-angelopolis-puebla-30731174","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Lomas de Angelópolis","neighborhood":"Lomas de Angelópolis","city":"San Andrés Cholula","state":"Puebla","price_amount":9190000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":4,"bathrooms":5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":415,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30731174","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30953563","source_url":"https://propiedades.com/inmuebles/casa-en-venta-parque-guanajuato-108-lomas-de-angelopolis-puebla-30953563","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Lomas de Angelópolis","neighborhood":"Lomas de Angelópolis","city":"San Andrés Cholula","state":"Puebla","price_amount":7750000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":4,"bathrooms":5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":362,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30953563","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"31363807","source_url":"https://propiedades.com/inmuebles/casa-en-venta-blvd-de-los-volcanes-890-lomas-de-angelopolis-puebla-31363807","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Lomas de Angelópolis","neighborhood":"Lomas de Angelópolis","city":"San Andrés Cholula","state":"Puebla","price_amount":6390000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":4,"bathrooms":4,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":298,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-31363807","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},

    {"source_code":"propiedades-com","external_reference":"28830021","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-boulevard-jardin-de-las-orquideas-3115-lago-tres-rios-sinaloa-28830021","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tres Ríos","neighborhood":"Desarrollo Urbano 3 Ríos","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1750000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":66,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"jardin-orquideas-3115","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"26239206","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-blvd-jardin-las-orquideas-3115-lago-tres-rios-sinaloa-26239206","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tres Ríos","neighborhood":"Desarrollo Urbano 3 Ríos","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1944000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":65,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"jardin-orquideas-3115","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"26664896","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-lago-tres-rios-sinaloa-26664896","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tres Ríos","neighborhood":"Desarrollo Urbano 3 Ríos","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2588395,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":1,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":46,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-26664896","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"28478634","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-boulevard-enrique-sanchez-alonso-2079-desarrollo-urbano-3-rios-sinaloa-28478634","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tres Ríos","neighborhood":"Desarrollo Urbano 3 Ríos","city":"Culiacán Rosales","state":"Sinaloa","price_amount":4900000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":82,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-28478634","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"29866125","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-desarrollo-urbano-3-rios-sinaloa-29866125","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tres Ríos","neighborhood":"Desarrollo Urbano 3 Ríos","city":"Culiacán Rosales","state":"Sinaloa","price_amount":3800000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":82,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-29866125","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"29968603","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-desarrollo-urbano-3-rios-sinaloa-29968603","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tres Ríos","neighborhood":"Desarrollo Urbano 3 Ríos","city":"Culiacán Rosales","state":"Sinaloa","price_amount":6950000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":134,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-29968603","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30283901","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-desarrollo-urbano-3-rios-sinaloa-30283901","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tres Ríos","neighborhood":"Desarrollo Urbano 3 Ríos","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2474000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":63,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30283901","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},

    {"source_code":"propiedades-com","external_reference":"31152382","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-avenida-presa-del-laurel-112-tetlan-jalisco-31152382","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tetlán","neighborhood":"Tetlán","city":"Guadalajara","state":"Jalisco","price_amount":2260000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":60,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"presa-laurel-112-2260","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"31587676","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-tetlan-tetlan-jalisco-31587676","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tetlán","neighborhood":"Tetlán","city":"Guadalajara","state":"Jalisco","price_amount":2180000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":60,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"presa-laurel-2180-60","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"29750969","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-guadalajara-tetlan-jalisco-29750969","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Tetlán","neighborhood":"Tetlán","city":"Guadalajara","state":"Jalisco","price_amount":1499000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":55,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-29750969","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},

    {"source_code":"propiedades-com","external_reference":"29755627","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-avenida-camaron-sabalo-561-zona-dorada-sinaloa-29755627","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Zona Dorada","neighborhood":"Zona Dorada","city":"Mazatlán","state":"Sinaloa","price_amount":10300000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":114,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-29755627","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"31165385","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-zona-dorada-sinaloa-31165385","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Zona Dorada","neighborhood":"Zona Dorada","city":"Mazatlán","state":"Sinaloa","price_amount":17500000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":3,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":201,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-31165385","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"31544021","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-av-gaviotas-zona-dorada-sinaloa-31544021","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Zona Dorada","neighborhood":"Zona Dorada","city":"Mazatlán","state":"Sinaloa","price_amount":10950000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":3,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":140,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-31544021","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"29973317","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-sin-nombre-de-calle-zona-dorada-sinaloa-29973317","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Zona Dorada","neighborhood":"Zona Dorada","city":"Mazatlán","state":"Sinaloa","price_amount":12401000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":147,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-29973317","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"31525354","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-av-vistahermosa-zona-dorada-sinaloa-31525354","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Zona Dorada","neighborhood":"Zona Dorada","city":"Mazatlán","state":"Sinaloa","price_amount":5500000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":155,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-31525354","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30374858","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-zona-dorada-sinaloa-30374858","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Zona Dorada","neighborhood":"Zona Dorada","city":"Mazatlán","state":"Sinaloa","price_amount":9000000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":3,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":265,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30374858","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"28300860","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-zona-dorada-zona-dorada-sinaloa-28300860","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Zona Dorada","neighborhood":"Zona Dorada","city":"Mazatlán","state":"Sinaloa","price_amount":2850000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":1,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":43,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-28300860","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"29724250","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-sierra-de-venados-lomas-de-mazatlan-zona-dorada-sinaloa-29724250","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Zona Dorada","neighborhood":"Zona Dorada","city":"Mazatlán","state":"Sinaloa","price_amount":3300000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":96,"quality_score":86,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-29724250","data_completeness":0.92,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true,"borderMarket":true}},
    {"source_code":"propiedades-com","external_reference":"30432720","source_url":"https://propiedades.com/inmuebles/departamento-en-venta-sin-nombre-de-calle-zona-dorada-sinaloa-30432720","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"APARTMENT","title":"Departamento comparable en Zona Dorada","neighborhood":"Zona Dorada","city":"Mazatlán","state":"Sinaloa","price_amount":10000000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":126,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30432720","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}}
  ]$rows$::jsonb
);

-- Additional ordinary-market houses. Known cross-portal matches share a
-- syndication fingerprint so they corroborate a home without inflating N.
select public.ingest_research_market_observations(
  $source${"source_code":"propiedades-com","organization":"Propiedades.com","name":"Propiedades.com — fichas públicas verificadas","official_url":"https://propiedades.com/","geographic_scope":"México","update_frequency":"on-demand","license_name":"Investigación comparativa de anuncios públicos","license_url":null,"metadata":{"usageAuthorization":"RESEARCH_ONLY","accessMethod":"PUBLIC_WEB_RESEARCH","researchBasis":"user-directed-comparative-market-research","researchScope":"minimal-asking-price-comparables","visibility":"internal","storedFieldsExclude":["phone","email","fullDescription","photos","sellerIdentity"]}}$source$::jsonb,
  $rows$[
    {"source_code":"propiedades-com","external_reference":"30421777","source_url":"https://propiedades.com/inmuebles/casa-en-venta-villas-del-rio-sinaloa-30421777","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2500000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":214,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"villas-rio-claveles-214","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30284247","source_url":"https://propiedades.com/inmuebles/casa-en-venta-villas-del-rio-sinaloa-30284247","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":3770000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":4,"bathrooms":3,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":246,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30284247","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"29119173","source_url":"https://propiedades.com/inmuebles/casa-en-venta-villa-cadiz-2925-villas-del-rio-sinaloa-29119173","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1750000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":71,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-29119173","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"29392526","source_url":"https://propiedades.com/inmuebles/casa-en-venta-rodolfo-manjarrez-2670-villas-del-rio-sinaloa-29392526","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1980000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":100,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-29392526","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30932375","source_url":"https://propiedades.com/inmuebles/casa-en-venta-villas-del-rio-sinaloa-30932375","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2150000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":111,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"villas-rio-2150-111","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"29816520","source_url":"https://propiedades.com/inmuebles/casa-en-venta-villas-del-rio-sinaloa-29816520","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2950000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":146,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-29816520","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30540513","source_url":"https://propiedades.com/inmuebles/casa-en-venta-sin-nombre-de-calle-villas-del-rio-sinaloa-30540513","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":3800000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":310,"quality_score":84,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30540513","data_completeness":0.90,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true,"genericAddress":true}},
    {"source_code":"propiedades-com","external_reference":"31099642","source_url":"https://propiedades.com/inmuebles/casa-en-venta-villas-del-rio-villas-del-rio-sinaloa-31099642","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2849000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":146,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"villas-rio-2849-146","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},

    {"source_code":"propiedades-com","external_reference":"31485736","source_url":"https://propiedades.com/inmuebles/casa-en-venta-urbivilla-del-cedro-80058-culiacan-rosales-sin-3463-villa-del-cedro-sinaloa-31485736","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable ordinaria en Villa del Cedro","neighborhood":"Villa del Cedro","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1750000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":76,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-31485736","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"27375203","source_url":"https://propiedades.com/inmuebles/casa-en-venta-blvd-paseo-del-roble-villa-del-cedro-sinaloa-27375203","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable ordinaria en Villa del Cedro","neighborhood":"Villa del Cedro","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2320000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":3,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":114,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-27375203","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"31060871","source_url":"https://propiedades.com/inmuebles/casa-en-venta-boulevard-del-universo-1-villa-del-cedro-sinaloa-31060871","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable ordinaria en Villa del Cedro","neighborhood":"Villa del Cedro","city":"Culiacán Rosales","state":"Sinaloa","price_amount":4459500,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":156,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-31060871","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30985506","source_url":"https://propiedades.com/inmuebles/casa-en-venta-villa-del-cedro-sinaloa-30985506","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable ordinaria en Villa del Cedro","neighborhood":"Villa del Cedro","city":"Culiacán Rosales","state":"Sinaloa","price_amount":3592160,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":3,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":180,"quality_score":88,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-30985506","data_completeness":0.92,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true,"genericAddress":true}},
    {"source_code":"propiedades-com","external_reference":"27847485","source_url":"https://propiedades.com/inmuebles/casa-en-venta-espino-4930-villa-del-cedro-sinaloa-27847485","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable ordinaria en Villa del Cedro","neighborhood":"Villa del Cedro","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1450000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":60,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"prop-27847485","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"propiedades-com","external_reference":"30705722","source_url":"https://propiedades.com/inmuebles/casa-en-venta-villa-del-cedro-sinaloa-30705722","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable ordinaria en Villa del Cedro","neighborhood":"Villa del Cedro","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1600000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":78,"quality_score":88,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"villa-cedro-1600-2r1b","data_completeness":0.92,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}}
  ]$rows$::jsonb
);

select public.ingest_research_market_observations(
  $source${
    "source_code":"inmuebles24",
    "organization":"Inmuebles24",
    "name":"Inmuebles24 — fichas públicas verificadas",
    "official_url":"https://www.inmuebles24.com/",
    "geographic_scope":"México",
    "update_frequency":"on-demand",
    "license_name":"Investigación comparativa de anuncios públicos",
    "license_url":null,
    "metadata":{"usageAuthorization":"RESEARCH_ONLY","accessMethod":"PUBLIC_WEB_RESEARCH","researchBasis":"user-directed-comparative-market-research","researchScope":"minimal-asking-price-comparables","visibility":"internal","storedFieldsExclude":["phone","email","fullDescription","photos","sellerIdentity"]}
  }$source$::jsonb,
  $rows$[
    {"source_code":"inmuebles24","external_reference":"149662274","source_url":"https://www.inmuebles24.com/propiedades/clasificado/veclcain-casa-en-venta-en-culiacan-149662274.html","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2849000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2.5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":146,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"villas-rio-2849-146","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"inmuebles24","external_reference":"142056978","source_url":"https://www.inmuebles24.com/propiedades/clasificado/veclcain-casa-en-fraccionamiento-villas-del-rio-142056978.html","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2500000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2.5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":214,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"villas-rio-claveles-214","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"inmuebles24","external_reference":"149463525","source_url":"https://www.inmuebles24.com/propiedades/clasificado/veclcain-casa-en-venta-en-villas-del-rio-149463525.html","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1600000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":72.35,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"i24-149463525","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"inmuebles24","external_reference":"149159430","source_url":"https://www.inmuebles24.com/propiedades/clasificado/veclcain-casa-en-fraccionamiento-villas-del-rio-149159430.html","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villas del Río","neighborhood":"Villas del Río","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2150000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":1.5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":111,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"i24-149159430","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"inmuebles24","external_reference":"144501829","source_url":"https://www.inmuebles24.com/propiedades/clasificado/veclcain-casa-en-venta-en-villa-del-cedro-culiacan-sinaloa-144501829.html","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villa del Cedro","neighborhood":"Villa del Cedro","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1485000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":2,"bathrooms":1,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":null,"surface_built_m2":92,"quality_score":90,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"abeto-1485-92","data_completeness":0.95,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true}},
    {"source_code":"inmuebles24","external_reference":"149865863","source_url":"https://www.inmuebles24.com/propiedades/clasificado/veclcain-casa-en-ventra-en-urbi-villa-del-cedros-de-4-149865863.html","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villa del Cedro","neighborhood":"Villa del Cedro","city":"Culiacán Rosales","state":"Sinaloa","price_amount":1920000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":4,"bathrooms":1.5,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":119,"surface_built_m2":null,"quality_score":84,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"i24-149865863","data_completeness":0.88,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true,"surfaceKind":"LAND_ONLY"}},
    {"source_code":"inmuebles24","external_reference":"150467006","source_url":"https://www.inmuebles24.com/propiedades/clasificado/veclcain--x1f3e1--x2728--casa-en-venta-en-bosques-del-rey-150467006.html","observation_kind":"ASKING_SALE","observation_date":"2026-08-10","property_type":"HOUSE","title":"Casa comparable en Villa del Cedro","neighborhood":"Villa del Cedro","city":"Culiacán Rosales","state":"Sinaloa","price_amount":2400000,"currency":"MXN","latitude":null,"longitude":null,"bedrooms":3,"bathrooms":2,"parking_spaces":null,"construction_age":null,"conservation_state":null,"surface_total_m2":117,"surface_built_m2":null,"quality_score":84,"parser_version":"towers-public-verification-v3","published_at":null,"last_verified_at":"2026-08-10T04:00:00Z","location_precision":"NEIGHBORHOOD","syndication_fingerprint":"i24-150467006","data_completeness":0.88,"attributes":{"collector":"public-page-verification","askingPrice":true,"publicationDateKnown":false,"researchOnly":true,"surfaceKind":"LAND_ONLY"}}
  ]$rows$::jsonb
);
