begin;

create schema if not exists territory;

revoke all on schema territory from public, anon, authenticated;
grant usage on schema territory to service_role;

create table if not exists territory.sources (
  code text primary key,
  organization text not null,
  title text not null,
  official_url text not null,
  source_role text not null check (source_role in ('primary', 'official_aggregator')),
  cadence text not null,
  geographic_coverage text not null,
  limitations jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists territory.releases (
  id uuid primary key default gen_random_uuid(),
  source_code text not null references territory.sources(code),
  external_release_id text,
  title text not null,
  period_start date,
  period_end date,
  retrieved_at timestamptz not null,
  asset_url text,
  content_sha256 text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (source_code, content_sha256)
);

create table if not exists territory.areas (
  id uuid primary key default gen_random_uuid(),
  geography_level text not null check (geography_level in ('NATION', 'STATE', 'MUNICIPALITY')),
  official_code text not null,
  name text not null,
  state_code text,
  state_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (geography_level, official_code)
);

create table if not exists territory.indicators (
  code text primary key,
  domain text not null check (domain in (
    'demographics',
    'economic_sectors',
    'employment',
    'income',
    'informality',
    'business_activity',
    'housing_need',
    'housing_market',
    'purchasing_power'
  )),
  label text not null,
  unit text not null,
  evidence_kind text not null check (evidence_kind in ('official_observation', 'official_projection')),
  methodology text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists territory.observations (
  id bigint generated by default as identity primary key,
  release_id uuid not null references territory.releases(id) on delete cascade,
  area_id uuid not null references territory.areas(id) on delete cascade,
  indicator_code text not null references territory.indicators(code),
  period_label text not null,
  value_numeric numeric,
  value_text text,
  dimensions jsonb not null default '{}'::jsonb,
  source_locator text not null,
  caveats jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  check (value_numeric is not null or value_text is not null),
  unique (release_id, area_id, indicator_code, period_label, dimensions)
);

create index if not exists territory_observations_area_indicator_idx
  on territory.observations (area_id, indicator_code, period_label);
create index if not exists territory_observations_dimensions_idx
  on territory.observations using gin (dimensions);
create index if not exists territory_areas_name_idx
  on territory.areas (lower(name));

alter table territory.sources enable row level security;
alter table territory.releases enable row level security;
alter table territory.areas enable row level security;
alter table territory.indicators enable row level security;
alter table territory.observations enable row level security;

revoke all on all tables in schema territory from public, anon, authenticated;
revoke all on all sequences in schema territory from public, anon, authenticated;
grant select, insert, update, delete on all tables in schema territory to service_role;
grant usage, select on all sequences in schema territory to service_role;

alter default privileges in schema territory revoke all on tables from public, anon, authenticated;
alter default privileges in schema territory revoke all on sequences from public, anon, authenticated;
alter default privileges in schema territory grant select, insert, update, delete on tables to service_role;
alter default privileges in schema territory grant usage, select on sequences to service_role;

insert into territory.sources (
  code,
  organization,
  title,
  official_url,
  source_role,
  cadence,
  geographic_coverage,
  limitations
) values
  (
    'inegi-enoe',
    'INEGI',
    'Encuesta Nacional de Ocupación y Empleo (ENOE)',
    'https://www.inegi.org.mx/programas/enoe/15ymas/',
    'primary',
    'Mensual y trimestral',
    'Nacional y estatal; ciudades autorrepresentadas seleccionadas',
    '["No es representativa para todos los municipios", "No permite inferir ingreso individual"]'::jsonb
  ),
  (
    'data-mexico-enoe',
    'Secretaría de Economía / INEGI',
    'Data México — cubo ENOE',
    'https://www.economia.gob.mx/datamexico/es/about/infoapi',
    'official_aggregator',
    'Trimestral',
    'Nacional y estatal',
    '["La fuente primaria subyacente es INEGI ENOE"]'::jsonb
  ),
  (
    'inegi-economic-census',
    'INEGI',
    'Censos Económicos',
    'https://www.inegi.org.mx/programas/ce/2024/',
    'primary',
    'Quinquenal',
    'Nacional, estatal y municipal',
    '["Es una línea base estructural, no una lectura mensual"]'::jsonb
  ),
  (
    'inegi-denue',
    'INEGI',
    'Directorio Estadístico Nacional de Unidades Económicas',
    'https://www.inegi.org.mx/servicios/api_denue.html',
    'primary',
    'Por edición',
    'Nacional a establecimiento',
    '["No representa todo el comercio informal", "La API requiere token oficial"]'::jsonb
  ),
  (
    'conapo-population-projections',
    'CONAPO',
    'Reconstrucción y proyecciones de población municipal 1990–2040',
    'https://www.datos.gob.mx/es/dataset/proyecciones-de-poblacion',
    'primary',
    'Por nueva corrida de proyección',
    'Nacional, estatal y municipal',
    '["Los años futuros son proyecciones", "Crecimiento no equivale a plusvalía"]'::jsonb
  ),
  (
    'sniiv-housing-backlog',
    'SEDATU / CONAVI',
    'SNIIV — rezago habitacional',
    'https://sniiv.sedatu.gob.mx/Reporte/Datos_abiertos',
    'primary',
    'Bienal estatal y censal municipal',
    'Estatal y municipal',
    '["Rezago social no equivale a demanda comercial"]'::jsonb
  ),
  (
    'sniiv-housing-financing',
    'SEDATU / CONAVI',
    'SNIIV — financiamiento y registro de vivienda',
    'https://sniiv.sedatu.gob.mx/Reporte/Datos_abiertos',
    'primary',
    'Mensual',
    'Nacional, estatal y municipal',
    '["No representa compraventas no registradas ni demanda no financiada"]'::jsonb
  )
on conflict (code) do update set
  organization = excluded.organization,
  title = excluded.title,
  official_url = excluded.official_url,
  source_role = excluded.source_role,
  cadence = excluded.cadence,
  geographic_coverage = excluded.geographic_coverage,
  limitations = excluded.limitations,
  active = true,
  updated_at = now();

comment on schema territory is
  'Datos territoriales oficiales agregados para inteligencia socioeconómica. Sin perfiles individuales ni segmentación por atributos protegidos.';
comment on table territory.observations is
  'Observaciones agregadas con procedencia por publicación, geografía, periodo y dimensiones.';

commit;
